package com.news.newsapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CATEGORY".
 */
@Entity
public class Category {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String category_name;
    private Boolean is_active_category;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    @Generated
    public Category(Long id, String category_name, Boolean is_active_category) {
        this.id = id;
        this.category_name = category_name;
        this.is_active_category = is_active_category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCategory_name() {
        return category_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_name(@NotNull String category_name) {
        this.category_name = category_name;
    }

    public Boolean getIs_active_category() {
        return is_active_category;
    }

    public void setIs_active_category(Boolean is_active_category) {
        this.is_active_category = is_active_category;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
