package com.news.newsapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String last_name;

    @NotNull
    private String first_name;

    @NotNull
    private String username;

    @NotNull
    private String email;

    @NotNull
    private String password;
    private Boolean is_active_user;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String last_name, String first_name, String username, String email, String password, Boolean is_active_user) {
        this.id = id;
        this.last_name = last_name;
        this.first_name = first_name;
        this.username = username;
        this.email = email;
        this.password = password;
        this.is_active_user = is_active_user;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getLast_name() {
        return last_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLast_name(@NotNull String last_name) {
        this.last_name = last_name;
    }

    @NotNull
    public String getFirst_name() {
        return first_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirst_name(@NotNull String first_name) {
        this.first_name = first_name;
    }

    @NotNull
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(@NotNull String username) {
        this.username = username;
    }

    @NotNull
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(@NotNull String email) {
        this.email = email;
    }

    @NotNull
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(@NotNull String password) {
        this.password = password;
    }

    public Boolean getIs_active_user() {
        return is_active_user;
    }

    public void setIs_active_user(Boolean is_active_user) {
        this.is_active_user = is_active_user;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
